# Generated by Django 4.1.7 on 2023-03-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='year',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
