# Generated by Django 4.1.7 on 2023-03-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_reviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='storyline',
            field=models.CharField(max_length=5000),
        ),
    ]
