# Generated by Django 4.1.7 on 2023-08-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviewer', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SimilarMovie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('backdrop_path', models.CharField(default='', max_length=255, null=True)),
                ('adult', models.BooleanField()),
                ('original_language', models.CharField(max_length=10)),
                ('original_title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('poster_path', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('video', models.BooleanField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('similar_to', models.IntegerField()),
                ('genre_ids', models.ManyToManyField(related_name='similar_movies', to='moviereviewer.genre')),
            ],
        ),
    ]
