# Generated by Django 4.1.7 on 2023-08-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviewer', '0003_alter_movie_backdrop_path_similarmovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('character_name', models.CharField(max_length=255)),
                ('profile_path', models.CharField(max_length=255)),
                ('movie_id', models.IntegerField()),
            ],
        ),
    ]
