# Generated by Django 4.1.7 on 2023-08-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviewer', '0005_alter_cast_profile_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('review_data', models.CharField(max_length=5000, null=True)),
                ('movie_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
