# Generated by Django 4.1.7 on 2023-10-21 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moviereviewer', '0007_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='original_title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='vote_average',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='vote_count',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='name',
        ),
        migrations.RemoveField(
            model_name='similarmovie',
            name='original_title',
        ),
        migrations.RemoveField(
            model_name='similarmovie',
            name='video',
        ),
        migrations.RemoveField(
            model_name='similarmovie',
            name='vote_average',
        ),
        migrations.RemoveField(
            model_name='similarmovie',
            name='vote_count',
        ),
        migrations.AddField(
            model_name='movie',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviews',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='similarmovie',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_similar_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
