# Generated by Django 4.1.7 on 2023-10-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviewer', '0008_remove_cast_movie_id_remove_movie_original_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='similarmovie',
            name='vote_average',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='similarmovie',
            name='vote_count',
            field=models.IntegerField(null=True),
        ),
    ]
