# Generated by Django 4.1.7 on 2023-10-29 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moviereviewer', '0012_reviews_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='share_by',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movies',
            field=models.ManyToManyField(null=True, related_name='watchlists', to='moviereviewer.movie'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='shared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_watchlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
