# Generated by Django 4.1.7 on 2023-10-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviewer', '0015_alter_watchlist_movies_alter_watchlist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
