# Generated by Django 4.1.7 on 2023-10-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviewer', '0016_alter_reviews_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
